DjangoWebProject/DjangoWebProject/urls.py
"""
Definition of urls for DjangoWebProject.
"""

from datetime import datetime
from django.conf.urls import url, include
from django.contrib import admin
import django.contrib.auth.views


admin.autodiscover()

urlpatterns = [

    url(r'^',include('movieapp.urls',namespace='movie')),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
]

DjangoWebProject/movieapp/urls.py
"""
Definition of urls for polls viewing and voting.
"""

from django.conf.urls import url

import movieapp.views

urlpatterns = [
    url(r'^$',
        movieapp.views.index,
        name='home'),
    url(r'^movie/(?P<pk>\d+)/$',
        movieapp.views.detail,
        name='detail'),
]

DjangoWebProject/movieapp/models.py
# -*- coding: UTF-8 *-*

from django.db import models

# Create your models here.

class Movie(models.Model):
    """Movie model for movieapp"""
    issrt_choice = (
        (0, '是'),
        (1, '否'),
    )
    language_choice = (
        (0, '国语'),
        (1, '外语'),
    )
    hd_choice = (
        (0, '1080P'),
        (1, '720P'),
        (2,'720P/1080P'),
    )
    type_choice =(
        (0,"动作片"),
        (1,"科幻片"),
        (2,"喜剧片"),
        (3,"恐怖片"),
        (4,"悬疑片"),
        (5,"剧情片"),
        (6,"动画片"),
        (7,"纪录片"),
        )
    area_choice =(
        (0,"中国/内地"),
        (1,"中国/香港"),
        (2,"美国"),
        (3,"欧洲"),
        (4,"日韩"),
        (5,"印度"),
        (6,"其他"),
        )

    title = models.CharField(u'电影名',max_length=50)
    img = models.CharField(u'电影海报',max_length=100)
    videopath = models.CharField(u'电影路径',max_length=200)
    filehd = models.IntegerField(u'高清类别',choices=hd_choice, default=0)
    description =models.TextField(u'电影简介')
    director = models.CharField(u'导演',max_length=10)
    actors = models.TextField(u'主要演员')
    mvtype = models.IntegerField(u'电影类型',choices=type_choice,default=0)
    mvarea = models.IntegerField(u'发行地区',choices=area_choice,default=0)
    language = models.IntegerField(u'电影语言',choices=language_choice, default=0)
    issrt = models.IntegerField(u'是否字幕',choices=issrt_choice, default=0)
    startyear = models.CharField(u'上映年份',max_length=10)
    star = models.IntegerField(u'豆瓣评分',default=0)
    xl720_id=models.IntegerField(u'迅雷ID',default=0)
    db_id=models.IntegerField(u'豆瓣ID',default=0)
    is_mv = models.IntegerField(u'是否电影',choices=issrt_choice,default=0)
    pub_date = models.DateTimeField(u'记录时间',auto_now_add=True)

    def __unicode__(self):
        return self.title

DjangoWebProject/movieapp/views.py
from django.shortcuts import render
from movieapp.models import Movie

# Create your views here.

def index(request):
    mvs = Movie.objects.all()[:14]
    mvnews = Movie.objects.all()[14:38]
    othermvs = Movie.objects.filter(is_mv=1)[:18]
    return render(
        request,
        'movieapp/index.html',
        {'hotmovies':mvs,
         'newmovies':mvnews,
         'othermvs':othermvs,
            })

def detail(request,pk):
    mv=Movie.objects.get(pk=pk)
    return render(
        request,
        'movieapp/detail.html',
        {'movie':mv,
         })

DjangoWebProject/movieapp/templates/movieapp/detail.html
{% extends "movieapp/layout.html" %}
{% load getdisplay %}

{% block content %}

<div id="content" role="main">
        <div id="post-35800" class="entry lazyload">
         <h1 class="postli-1">{{movie.title}}</h1>
    <div class="entry-meta clearfix">
        <span class="meta-author">类型：<a href="https://www.xl720.com/category/juqingpian" rel="category tag">{{movie|displayName:"mvtype"}}</a></span>
        <span class="meta-sep">|</span> <span class="meta-date" title="{{movie.pub_date}}">发布：{{movie.pub_date}}</span>
        <span class="meta-sep">|</span> <span class="meta-comments"><a href="https://www.xl720.com/thunder/{{movie.xl720_id}}.html#respond" target="_blank" rel="nofollow">去抢片子</a></span> 
        <span class="meta-sep">|</span> <span class="meta-comments"><a href="https://movie.douban.com/subject/{{movie.db_id}}/" target="_blank" rel="nofollow">豆瓣影评</a></span>
    </div>
    <div class="entry-content">
      <div class="subject">
        <div id="mainpic">
            <img class="alignnone size-full wp-image-35801" src="{{movie.img}}" alt="{{movie.title}}" width="150" height="210" original="https://www.xl720.com/uploads/2019/06/p2560176927.jpg">
            <p class="entry-rating">豆瓣 <strong>{{movie.star|db_star}}</strong> 分</p>
        </div>
        <div id="info">导演: <a href="https://www.xl720.com/thunder/writers/%e9%99%88%e5%92%8f%e7%87%8a" rel="bookmark">{{movie.director}}</a>
            <br> 主演: {{movie.actors}}
            <br> 类型: {{movie|displayName:"mvtype"}}
            <br> 制片国家/地区: <a href="https://www.xl720.com/thunder/area/xianggang" rel="bookmark">{{movie|displayName:"mvarea"}}</a>
            <br> 语言: {{movie|displayName:"language"}}
            <br> 上映日期: {{movie.startyear}}(中国大陆) / <a href="https://www.xl720.com/thunder/years/2018" rel="bookmark">2018</a>-08-02(香港)
        </div>
        <div class="gray" style="clear: bothfloat: left;"><a href="javascript:;" onclick="slideDiv();return false;" id="m_txt">&gt;&gt; 更多 &lt;&lt;</a></div>
    </div>
    <div class="clearfix" style="clear: both;"></div>
    <h2>{{movie.title}}的剧情介绍&nbsp;·&nbsp;·&nbsp;·&nbsp;·&nbsp;·&nbsp;·</h2>
    <div id="link-report">{{movie.description}}…&nbsp;</div><div id="content_btn"><a href="javascript:;" onclick="show_content();return false;">[ 显示全部剧情 ]</a></div>
    
    
    </div>
                           
   <div class="mvcontainer">
	<div class="row">
		<div class="col-md-12">
			<div id="willesPlay">
	<div class="playHeader">
		<div class="videoName">《{{movie.title}}》</div>
	</div>
	<div class="playContent">
				<video width="100%" height="100%" id="playVideo">
			<source src="/static/{{movie.videopath}}" type="video/mp4"></source>
			当前浏览器不支持 video直接播放，点击这里下载视频： <a href="http://www.52player.com">下载视频</a>
		</video>
		<div class="playTip glyphicon glyphicon-play"></div>
	</div>
	<div class="playControll">
		<div class="playPause playIcon"></div>
		<div class="timebar">
			<span class="currentTime">0:00:00</span>
			<div class="progress">
				<div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
				</div>
			<span class="duration">0:00:00</span>
		</div>
		<div class="otherControl">
			<span class="volume glyphicon glyphicon-volume-down"></span>
			<span class="fullScreen glyphicon glyphicon-fullscreen"></span>
			<div class="volumeBar">
					<div class="volumewrap">
						<div class="progress">
						<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: 8px;height: 40%;"></div>
					</div>
						</div>
				</div>
		</div>
	</div>
</div>
			
		</div>
	</div>
</div>



</div>
</div>





{% endblock %}

DjangoWebProject/movieapp/templates/movieapp/index.html
{% extends "movieapp/layout.html" %}
{% load getdisplay %}

{% block content %}

<div class="lazyload" id="homepage" role="main">

<div class="home-top clearfix">
    <div id="slider-wrap">
      <div class="cat-title clearfix"><h2>热片推荐</h2></div>
      <div class="slider clearfix">
        <ul>
        {% for item in hotmovies %}
            {% url 'movie:detail' item.id as the_url %}
            <li {{forloop.counter|setEndClass:"7"}}><a href="{{the_url}}" title="{{item.title}}" rel="bookmark">
              <div class="top-posters"><img src="{{item.img}}" alt="{{item.title}}" height="170" width="120" original="{{item.img}}"></div>
              <div class="cap">{{item.title}}</div></a><div class="entry-rating">{{item|displayName:"filehd"}}</div></li>
        {% endfor %}       
        </ul>
    </div></div>
</div>

<div id="home-left" class="clearfix"><div class="new-cat-title clearfix"><h2>最新电影</h2><span><a href="https://www.xl720.com/new" title="查看完整更新列表" rel="bookmark">更多 »</a></span></div>
    <div class="new-home-box clearfix">
        <ul>
            {% for item in newmovies %}
            <li {{forloop.counter|setEndClass:"6"}}>
                {% url 'movie:detail' item.id as the_url %}
                <a href="{{the_url}}" title="{{item.title}}" rel="bookmark">
                    <div class="posters">
                        <img src="{{item.img}}" alt="{{item.title}}" height="130" width="90" original="{{item.img}}">
                    </div><div class="cap">
                        {{item.title}}
                    </div>
                </a>
            </li>     
            {% endfor %}
        </ul>
    </div>
    <div class="new-cat-title n-title-distance clearfix"><h2>最新电视剧</h2></div><div class="new-home-box clearfix">
        <ul>
            {% for item in othermvs %}
            {% url 'movie:detail' item.id as the_url %}
           <li class="new"><a href="{{the_url}}" title="{{item.title}}" rel="bookmark">
               <div class="posters"><img src="{{item.img}}" alt="{{item.title}}" height="130" width="90" original="{{item.img}}" style="display: inline;"></div>
               <div class="cap">{{item.title}}</div></a><div class="entry-rating">连载 7 集</div>
           </li>
            {% endfor %}
        </ul>
    </div>
    </div>

<div id="home-right" class="clearfix">
    <div class="top-cat-title clearfix"><h2>本月电影排行</h2><span><a href="https://www.xl720.com/top" title="查看完整排行榜" rel="bookmark">更多 »</a></span></div>
    <div class="top-home-box clearfix">
      <ul>
        <li class="  topthree"><div class="top_number">01</div><a class="t-title" href="https://www.xl720.com/thunder/34559.html" title="海市蜃楼 Durante la tormenta (2018) 迅雷下载" rel="bookmark">海市蜃楼 Durante la tormenta (2018)</a></li>
        <li class="  topthree"><div class="top_number">02</div><a class="t-title" href="https://www.xl720.com/thunder/35055.html" title="流浪地球 (2019) 迅雷下载" rel="bookmark">流浪地球 (2019)</a></li>
        <li class="  topthree"><div class="top_number">03</div><a class="t-title" href="https://www.xl720.com/thunder/35466.html" title="惊奇队长 Captain Marvel (2019) 迅雷下载" rel="bookmark">惊奇队长 Captain Marvel (2019)</a></li>
        <li class=" "><div class="top_number">04</div><a class="t-title" href="https://www.xl720.com/thunder/34684.html" title="驯龙高手3 How To Train Your Dragon: The Hidden World (2019) 迅雷下载" rel="bookmark">驯龙高手3 How To Train Your Dragon: The Hidden World (2019)</a></li>
        <li class=" "><div class="top_number">05</div><a class="t-title" href="https://www.xl720.com/thunder/35024.html" title="盗梦特攻队 Ruben Brandt, a gyüjtö (2018) 迅雷下载" rel="bookmark">盗梦特攻队 Ruben Brandt, a gyüjtö (2018)</a></li>
        <li class=" "><div class="top_number">06</div><a class="t-title" href="https://www.xl720.com/thunder/34644.html" title="飞驰人生 (2019) 迅雷下载" rel="bookmark">飞驰人生 (2019)</a></li>
        <li class=" "><div class="top_number">07</div><a class="t-title" href="https://www.xl720.com/thunder/35650.html" title="大侦探皮卡丘 Pokémon Detective Pikachu (2019) 迅雷下载" rel="bookmark">大侦探皮卡丘 Pokémon Detective Pikachu (2019)</a></li>
        <li class=" "><div class="top_number">08</div><a class="t-title" href="https://www.xl720.com/thunder/35139.html" title="老师·好 (2019) 迅雷下载" rel="bookmark">老师·好 (2019)</a></li>
        <li class=" "><div class="top_number">09</div><a class="t-title" href="https://www.xl720.com/thunder/35163.html" title="冷血追击 Cold Pursuit (2019) 迅雷下载" rel="bookmark">冷血追击 Cold Pursuit (2019)</a></li>
        <li class=" "><div class="top_number">10</div><a class="t-title" href="https://www.xl720.com/thunder/34766.html" title="密室逃生 Escape Room (2019) 迅雷下载" rel="bookmark">密室逃生 Escape Room (2019)</a></li>
        <li class=" "><div class="top_number">11</div><a class="t-title" href="https://www.xl720.com/thunder/34571.html" title="三重威胁之跨国大营救 Triple Threat (2019) 迅雷下载" rel="bookmark">三重威胁之跨国大营救 Triple Threat (2019)</a></li>
        <li class=" "><div class="top_number">12</div><a class="t-title" href="https://www.xl720.com/thunder/34990.html" title="风中有朵雨做的云 (2019) 迅雷下载" rel="bookmark">风中有朵雨做的云 (2019)</a></li>
        <li class=" "><div class="top_number">13</div><a class="t-title" href="https://www.xl720.com/thunder/34695.html" title="无主之作 Werk ohne Autor (2018) 迅雷下载" rel="bookmark">无主之作 Werk ohne Autor (2018)</a></li>
        <li class=" "><div class="top_number">14</div><a class="t-title" href="https://www.xl720.com/thunder/34764.html" title="玻璃先生 Glass (2019) 迅雷下载" rel="bookmark">玻璃先生 Glass (2019)</a></li>
        <li class=" "><div class="top_number">15</div><a class="t-title" href="https://www.xl720.com/thunder/35178.html" title="为家而战 Fighting with My Family (2019) 迅雷下载" rel="bookmark">为家而战 Fighting with My Family (2019)</a></li>
        <li class=" "><div class="top_number">16</div><a class="t-title" href="https://www.xl720.com/thunder/34728.html" title="诡怪疑云 Aterrados (2017) 迅雷下载" rel="bookmark">诡怪疑云 Aterrados (2017)</a></li>
      </ul>
    </div>

    <div class="top-cat-title title-distance clearfix"><h2>本月电视剧排行</h2></div><div class="top-home-box clearfix">
      <ul>
        <li><a class="n-title" href="https://www.xl720.com/thunder/34909.html" title="权力的游戏 第八季 Game of Thrones Season 8 (2019) 迅雷下载" rel="bookmark">权力的游戏 第八季 Game of Thrones Season 8 (2019)</a></li>
        <li><a class="n-title" href="https://www.xl720.com/thunder/34755.html" title="我们与恶的距离 我們與惡的距離 (2019) 迅雷下载" rel="bookmark">我们与恶的距离 我們與惡的距離 (2019)</a></li>
        <li><a class="n-title" href="https://www.xl720.com/thunder/34265.html" title="倚天屠龙记 (2019) 迅雷下载" rel="bookmark">倚天屠龙记 (2019)</a></li>
        <li><a class="n-title" href="https://www.xl720.com/thunder/29355.html" title="氪星 Krypton (2018) 迅雷下载" rel="bookmark">氪星 Krypton (2018)</a></li>
        <li><a class="n-title" href="https://www.xl720.com/thunder/35224.html" title="破冰行动 (2019) 迅雷下载" rel="bookmark">破冰行动 (2019)</a></li>
        <li><a class="n-title" href="https://www.xl720.com/thunder/33750.html" title="怒晴湘西 (2019) 迅雷下载" rel="bookmark">怒晴湘西 (2019)</a></li>
        <li><a class="n-title" href="https://www.xl720.com/thunder/34241.html" title="黄金瞳 (2019) 迅雷下载" rel="bookmark">黄金瞳 (2019)</a></li>
        <li><a class="n-title" href="https://www.xl720.com/thunder/35195.html" title="切尔诺贝利 Chernobyl (2019) 迅雷下载" rel="bookmark">切尔诺贝利 Chernobyl (2019)</a></li>
        <li><a class="n-title" href="https://www.xl720.com/thunder/34568.html" title="囚犯医生 닥터 프리즈너 (2019) 迅雷下载" rel="bookmark">囚犯医生 닥터 프리즈너 (2019)</a></li>
        <li><a class="n-title" href="https://www.xl720.com/thunder/31193.html" title="延禧攻略 (2018) 迅雷下载" rel="bookmark">延禧攻略 (2018)</a></li>
        <li><a class="n-title" href="https://www.xl720.com/thunder/32629.html" title="将夜 (2018) 迅雷下载" rel="bookmark">将夜 (2018)</a></li>
        <li><a class="n-title" href="https://www.xl720.com/thunder/33103.html" title="大帅哥 大帥哥 (2018) 迅雷下载" rel="bookmark">大帅哥 大帥哥 (2018)</a></li>
        <li><a class="n-title" href="https://www.xl720.com/thunder/27534.html" title="虎啸龙吟 (2017) 迅雷下载" rel="bookmark">虎啸龙吟 (2017)</a></li>
        <li><a class="n-title" href="https://www.xl720.com/thunder/33813.html" title="王国 킹덤 (2019) 迅雷下载" rel="bookmark">王国 킹덤 (2019)</a></li>
        <li><a class="n-title" href="https://www.xl720.com/thunder/35324.html" title="未来岁月 Years and Years (2019) 迅雷下载" rel="bookmark">未来岁月 Years and Years (2019)</a></li>
      </ul>
    </div>
</div>

</div>


{% endblock %}

DjangoWebProject/movieapp/templates/movieapp/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Django App</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'movieapp/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'movieapp/content/core.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'movieapp/content/reset.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'movieapp/content/willesPlay.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'movieapp/content/site.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'movieapp/content/mysite.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">🔣|电|🔣|影|🔣|很|🔣|酷|🔣</a>
            </div>
            <div class="navbar-collapse collapse">            
                <form class="navbar-form navbar-right">
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">搜索一下</button>
                 </form>
            </div>
        </div>
    </div>

    <div class="container body-content" id="wrapper">
        <div id="main" class="clearfix">
{% block content %}{% endblock %}
            </div>
        </div>

    <div id="footer"><div class="wrap"><p>© 2019 <strong>电影库</strong>. All rights reserved.</p><p></p><p>电影库——最新高清迅雷电影电视剧网站</p><p>本站所有资源来自互联网，如果无意中侵犯了您的权利，请与我们联系</p></div></div>


    <script src="{% static 'movieapp/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'movieapp/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'movieapp/scripts/respond.js' %}"></script>
        <script src="{% static 'movieapp/js/willesPlay.js' %}"></script>
 
    {% block scripts %}{% endblock %}

</body>
</html>